In [1]:
import numpy as np
import operator

def createDataSet():
    # 四组二维特征
    group = np.array([[1.0,1.1],[1.0,1.0],[0,0],[0,0.1]])
    # 四组特征的标签
    labels = ['A','A','B','B']
    return group, labels

In [2]:
group, labels = createDataSet()

In [5]:
dataSetSize = group.shape[0]
print(dataSetSize)

4


In [8]:
diffMat = np.tile([0,0], (dataSetSize, 1)) - group
print(diffMat)

[[-1.  -1.1]
 [-1.  -1. ]
 [ 0.   0. ]
 [ 0.  -0.1]]


In [10]:
sqDiffMat = diffMat**2
print(sqDiffMat)

[[1.   1.21]
 [1.   1.  ]
 [0.   0.  ]
 [0.   0.01]]


In [11]:
sqDistances = sqDiffMat.sum(axis=1)
print(sqDistances)

[2.21 2.   0.   0.01]


In [12]:
distances = sqDistances**0.5
print(distances)

[1.48660687 1.41421356 0.         0.1       ]


In [13]:
sortedDistIndicies = distances.argsort()
print(sortedDistIndicies)

[2 3 1 0]


In [17]:
for i in range(k):
    print(i)

0
1
2


In [15]:
k = 3
classCount = {}
# 选择距离最小的k个点
for i in range(k):
    # 取出前k个元素的类别
    voteIlabel = labels[sortedDistIndicies[i]]
    # 字典的get()方法，返回指定键的值，如果值不在字典中返回0
    # 计算类别次数
    classCount[voteIlabel] = classCount.get(voteIlabel, 0) + 1

In [16]:
classCount

{'B': 2, 'A': 1}

In [18]:
sortedClassCount = sorted(classCount.items(),
                            key = operator.itemgetter(1), reverse = True)
print(sortedClassCount)

[('B', 2), ('A', 1)]


In [20]:
type(sortedClassCount[0])

tuple

## 文件读取

In [1]:
import numpy as np

In [3]:
filename = "datingTestSet.txt"

In [4]:
fr = open(filename)
# 读取文件所有内容
arrayOlines = fr.readlines()
# 得到文件行数
numberOfLines = len(arrayOlines)
# 返回的NumPy矩阵numberOfLines行，3列
returnMat = np.zeros((numberOfLines, 3))
# 创建分类标签向量
classLabelVector = []
# 行的索引值
index = 0
# 读取每一行
for line in arrayOlines:
    # 去掉每一行首尾的空白符，例如'\n','\r','\t',' '
    line = line.strip()
    # 将每一行内容根据'\t'符进行切片,本例中一共有4列
    listFromLine = line.split('\t')

In [7]:
listFromLine[0:3]

['43757', '7.882601', '1.332446']

In [8]:
listFromLine

['43757', '7.882601', '1.332446', 'largeDoses']